/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpa.routeoptimizer.views;

import java.util.ArrayList;
import tpa.routeoptimizer.lib.Grafo;

/**
 *
 * @author lume
 */
public class AddRoute extends javax.swing.JFrame {

    Grafo grapho;
    boolean is_combo = false;

    /**
     * Creates new form AddCity
     */
    public AddRoute(Grafo newGrafo) {
        setUndecorated(true);

        initComponents();
        this.setLocationRelativeTo(null);

        grapho = newGrafo;
        ArrayList<String> cidades = grapho.obterVerticesValues();
        
        for (String cidade : cidades) {
            originComboBox.addItem(cidade);
            destinyComboBox.addItem(cidade);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addCityButton = new javax.swing.JButton();
        cityOriginNameField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        destinyLabel = new javax.swing.JLabel();
        feedBackField = new javax.swing.JLabel();
        cityDestinyNameField = new javax.swing.JTextField();
        originLabel = new javax.swing.JLabel();
        distanceField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        switchSelecMethodButton = new javax.swing.JButton();
        originComboBox = new javax.swing.JComboBox<>();
        destinyComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Addicionar Rota");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 46, 238, 39));

        addCityButton.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        addCityButton.setText("+");
        addCityButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCityButtonMouseClicked(evt);
            }
        });
        getContentPane().add(addCityButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 67, 52));
        getContentPane().add(cityOriginNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 169, 242, 40));

        cancelButton.setText("Voltar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 318, 121, 34));

        destinyLabel.setText("Digite a cidade de destino");
        getContentPane().add(destinyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 214, -1));
        getContentPane().add(feedBackField, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 269, 28));
        getContentPane().add(cityDestinyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 242, 45));

        originLabel.setText("Digite a cidade de origem:");
        getContentPane().add(originLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 132, 214, -1));
        getContentPane().add(distanceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 242, 45));

        jLabel4.setText("Distancia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 214, -1));

        switchSelecMethodButton.setText("Alterar metodo de seleção");
        switchSelecMethodButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchSelecMethodButtonMouseClicked(evt);
            }
        });
        getContentPane().add(switchSelecMethodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 210, 30));
        getContentPane().add(originComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 230, 40));
        getContentPane().add(destinyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 230, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 480, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCityButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCityButtonMouseClicked
        String cityOrigin;
        String cityDestiny;

        if (is_combo) {
            cityOrigin = ((String) originComboBox.getSelectedItem());
            cityDestiny = ((String) destinyComboBox.getSelectedItem());
        }
        else{
            cityOrigin = cityOriginNameField.getText().toLowerCase().trim();
            cityDestiny = cityDestinyNameField.getText().toLowerCase().trim();
        }
        String distance = distanceField.getText();

        if (cityOrigin != null && !cityOrigin.trim().isEmpty()) {
            if (grapho.obterVertice(cityOrigin) == null) {
                grapho.adicionarVertice(cityOrigin);  // Adiciona o vértice se não existir
                feedBackField.setText("Cidade de origem adicionada com sucesso!");
            } else {
                feedBackField.setText("Cidade de origem já existe!");
            }
        } else {
            feedBackField.setText("Nome da cidade de origem inválido.");
            return;
        }

        if (cityDestiny != null && !cityDestiny.trim().isEmpty()) {
            if (grapho.obterVertice(cityDestiny) == null) {
                grapho.adicionarVertice(cityDestiny);  // Adiciona o vértice se não existir
                feedBackField.setText("Cidade de destino adicionada com sucesso!");
            } else {
                feedBackField.setText("Cidade de destino já existe!");
            }
        } else {
            feedBackField.setText("Nome da cidade de destino inválido.");
            return;
        }

        try {
            float dist = Float.parseFloat(distance);
            grapho.adicionarAresta(cityOrigin, cityDestiny, dist);
            feedBackField.setText("Aresta adicionada com sucesso!");
        } catch (NumberFormatException e) {
            feedBackField.setText("Distância inválida. Por favor, insira um número válido.");
        }
    }//GEN-LAST:event_addCityButtonMouseClicked

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void switchSelecMethodButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchSelecMethodButtonMouseClicked
          if(!is_combo){
              is_combo = true;
              cityDestinyNameField.setVisible(false);
              cityOriginNameField.setVisible(false);
              destinyComboBox.setVisible(true);
              originComboBox.setVisible(true);
              destinyLabel.setText("Selecione uma cidade de destino:");
              originLabel.setText("Selecione uma cidade de origem:");

          }else{
            is_combo = false;
            cityDestinyNameField.setVisible(true);
            cityOriginNameField.setVisible(true);
            destinyComboBox.setVisible(false);
            originComboBox.setVisible(false);
            destinyLabel.setText("Digite uma cidade de destino:");
            originLabel.setText("Digite uma cidade de origem:");
          }        // TODO add your handling code here:
    }//GEN-LAST:event_switchSelecMethodButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRoute.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCityButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cityDestinyNameField;
    private javax.swing.JTextField cityOriginNameField;
    private javax.swing.JComboBox<String> destinyComboBox;
    private javax.swing.JLabel destinyLabel;
    private javax.swing.JTextField distanceField;
    private javax.swing.JLabel feedBackField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> originComboBox;
    private javax.swing.JLabel originLabel;
    private javax.swing.JButton switchSelecMethodButton;
    // End of variables declaration//GEN-END:variables
}
