/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tpa.routeoptimizer.views;

import java.util.ArrayList;
import tpa.routeoptimizer.lib.Grafo;
import tpa.routeoptimizer.lib.Vertice;

/**
 *
 * @author lume
 */
public class DistanceBetweenCitys extends javax.swing.JFrame {

    Grafo grapho;
    boolean is_combo = false;
    /**
     * Creates new form AddCity
     */
    public DistanceBetweenCitys(Grafo newGrafo) {
        setUndecorated(true);

        initComponents();
        this.setLocationRelativeTo(null);
        
        grapho = newGrafo;
        
        ArrayList<String> cidades = grapho.obterVerticesValues();
        
        for (String cidade : cidades) {
            originComboBox.addItem(cidade);
            destinyComboBox.addItem(cidade);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        calcDistButton = new javax.swing.JButton();
        switchSelecMethodButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        routeField = new javax.swing.JTextArea();
        cityDestinyNameField = new javax.swing.JTextField();
        feedBackField = new javax.swing.JLabel();
        originLabel = new javax.swing.JLabel();
        destinyLabel = new javax.swing.JLabel();
        cityOriginNameField = new javax.swing.JTextField();
        distanceLabel = new javax.swing.JLabel();
        originComboBox = new javax.swing.JComboBox<>();
        destinyComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel1.setText("Calcula Distancia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 238, 39));

        calcDistButton.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        calcDistButton.setText("Calcule");
        calcDistButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcDistButtonMouseClicked(evt);
            }
        });
        getContentPane().add(calcDistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 200, 74));

        switchSelecMethodButton.setText("Alterar metodo de seleção");
        switchSelecMethodButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchSelecMethodButtonMouseClicked(evt);
            }
        });
        getContentPane().add(switchSelecMethodButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, -1, 40));

        cancelButton.setText("Voltar");
        cancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelButtonMouseClicked(evt);
            }
        });
        getContentPane().add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 740, 121, 34));

        routeField.setColumns(20);
        routeField.setRows(5);
        getContentPane().add(routeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 760, 200));
        getContentPane().add(cityDestinyNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 279, 291, 45));
        getContentPane().add(feedBackField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 560, 28));

        originLabel.setText("Digite a cidade de destino");
        getContentPane().add(originLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 238, 214, -1));

        destinyLabel.setText("Digite a cidade de origem:");
        getContentPane().add(destinyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 359, 214, -1));
        getContentPane().add(cityOriginNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 291, 57));

        distanceLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        getContentPane().add(distanceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 395, 291, 65));
        getContentPane().add(originComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 280, 40));
        getContentPane().add(destinyComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 270, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 800, 910, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelButtonMouseClicked
        // TODO add your handling code here:

        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonMouseClicked

    private void calcDistButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calcDistButtonMouseClicked
        String cityOrigin;
        String cityDestiny;

        if (is_combo) {
            cityOrigin = ((String) originComboBox.getSelectedItem());
            cityDestiny = ((String) destinyComboBox.getSelectedItem());
        }
        else{
            cityOrigin = cityOriginNameField.getText().toLowerCase().trim();
            cityDestiny = cityDestinyNameField.getText().toLowerCase().trim();
        }
        if (cityOrigin != null && !cityOrigin.isEmpty() && cityDestiny != null && !cityDestiny.isEmpty()) {
            try {
                grapho.calcMinRoute(cityOrigin, cityDestiny,routeField);
                feedBackField.setText("Sucesso!");
            } catch (IllegalArgumentException e) {
                feedBackField.setText(e.getMessage());
            }
        } else {
            feedBackField.setText("Nome da cidade de origem ou destino inválido.");
        }    
    }//GEN-LAST:event_calcDistButtonMouseClicked

    private void switchSelecMethodButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchSelecMethodButtonMouseClicked
          if(!is_combo){
              is_combo = true;
              cityDestinyNameField.setVisible(false);
              cityOriginNameField.setVisible(false);
              destinyComboBox.setVisible(true);
              originComboBox.setVisible(true);
              destinyLabel.setText("Selecione uma cidade de destino:");
              originLabel.setText("Selecione uma cidade de origem:");

          }else{
            is_combo = false;
            cityDestinyNameField.setVisible(true);
            cityOriginNameField.setVisible(true);
            destinyComboBox.setVisible(false);
            originComboBox.setVisible(false);
            destinyLabel.setText("Digite uma cidade de destino:");
            originLabel.setText("Digite uma cidade de origem:");
          }    
    }//GEN-LAST:event_switchSelecMethodButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistanceBetweenCitys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistanceBetweenCitys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistanceBetweenCitys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistanceBetweenCitys.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcDistButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cityDestinyNameField;
    private javax.swing.JTextField cityOriginNameField;
    private javax.swing.JComboBox<String> destinyComboBox;
    private javax.swing.JLabel destinyLabel;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JLabel feedBackField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> originComboBox;
    private javax.swing.JLabel originLabel;
    private javax.swing.JTextArea routeField;
    private javax.swing.JButton switchSelecMethodButton;
    // End of variables declaration//GEN-END:variables
}
